### PR TITLE
Add check for presence of HTTP::Tiny

### PR DESCRIPTION
**Pull request by michal-josef-spacek**
HTTP::Tiny is not required and it's fine to have some message.

### CODE REVIEW

**Comment by briandfoy** [comment]
Is there something that's not happening as you except? HTTP::Tiny has been part of the standard library since v5.14.

In this patch, if you don't find HTTP::Tiny, I don't think the program can continue. A better error message is good, but at the same time, the program needs to stop immediately.

**Comment by michal-josef-spacek** [comment]
@briandfoy The root cause that we are trying to resolve is the situation in Fedora/RHEL where there is a different granularity of packages (modules) than in Perl Core. Perl distribution is ~~ perl package, but there are perl-interpreter and other modules in the hierarchy. After adding IO::Socket::SSL dependency to HTTP::Tiny is hierarchy bigger and the reality is that Pod::Perldoc has dependencies to networking, which we don't need. As I understand this code block is used only in the situation when I call ```perldoc https://fastapi.metacpan.org/source/SKIM/App-Pod-Example-0.20/Example.pm``` which is not much used. I am going to change the dependency of HTTP::Tiny to not strict in Fedora RPM dependencies. In this situation, I need to be ok with functionality.

ad functionality) If IO::Socket::SSL is not present and the message "You may need an SSL library (such as IO::Socket::SSL) for that URL." is printed, that's a similar situation, sure? (There is no exit or die too)

btw: I believe that the check of every usage of ```require``` is needed. My experiences are that sometimes the module isn't present (due to issues on disk, whatever), and it is fine to handle this situation properly.

**Comment by briandfoy** [comment]
I'm not opposed to the change, but you have to end the program if the module is not found, like I noted earlier. This change has to work for everyone and in the same way it did before. That is, it needs to die when it tries to require a module that is not present. As we have to support all uses of this Standard Library module, your change has to work for the all the current uses from everyone else in the world. It has to use the same exit value and give them same message (or we have to think carefully about the message). There have been issues in other cases where changing error messages have affected users. But, the best way to do that is to make no change.

It sounds like your plans actually violate the Artistic License, section 4. We all know that some thin systems have been hacking up perl such that the standard library cannot be run and are technically in violation. Since Pod::Perldoc is part of the standard library and you want to modify it so you can allow distributions that reduce its functionality, you (or whoever) cannot call it "perl" or "pod-perldoc" anymore, strictly speaking. The GPL has less strict language but also requires prominent notices of your changes.

If you are making this change for internal uses only, that's not a violation. You can do whatever you like. In that case, applying your own patch to a pinned version is probably better.

If you are planning to distribute your changes, you are violating the license. Not only that, but you would need to change the documentation of the modified module to note how you modified it to potentially remove features or required extra steps to restore functionality. For example, the message for a missing HTTP::Tiny would have to explain how the user of your setup need to proceed (such as showing the package manager command to install the proper packages). That's not something I'd want to track in this repository.

**Comment by michal-josef-spacek** [comment]
About functionality.

1)
The actual situation is (after removing IO::Socket::SSL from the system):
```
woman:~> perldoc https://fastapi.metacpan.org/source/SKIM/Tags-HTML-Page-End-0.06/End.pm
No documentation found for "https://fastapi.metacpan.org/source/SKIM/Tags-HTML-Page-End-0.06/End.pm".
You may need an SSL library (such as IO::Socket::SSL) for that URL.
woman:~> echo $?
1
```
This is simply not true. Documentation exists. The tool cannot process web page because of some consequences.

2) 
As I understand, You are saying that there is an error in the case when HTTP::Tiny is not present.
```
woman:~> perldoc https://fastapi.metacpan.org/source/SKIM/Tags-HTML-Page-End-0.06/End.pm
Can't locate HTTP/Tiny.pm in @INC (you may need to install the HTTP::Tiny module) (@INC contains: /home/skim/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/skim/perl5/lib/perl5 /home/skim/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/skim/perl5/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/x86_64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at /home/skim/perl5/lib/perl5/Pod/Perldoc.pm line 842.
woman:~> echo $?
2
```
Yes.

3) 
From my perspective as a user who is using the tool, I need to see what the issue is.
In the case of 1) I need to see that there are missing libraries.
In the case of 2) I need to see that there are missing libraries.
My proposal is to improve the message on output in case 2) in a similar way as in case 1).
die is called after the end of the block of these cases.
Yes, this is the API change, the error message change, and the exit code change.

4) 
About the change.
I am for the changing of error messages to something readable for the user.

**Comment by michal-josef-spacek** [comment]
About license etc.:
The actual situation in Fedora/RHEL which is valid for some years:
I could install perl package, which depends on 187 packages and all together are full Perl distribution.
I could install perl-interpreter alone or with explicit packages to build own installation.
That's it. 
If you think that something is wrong, we could communicate directly.

**Comment by briandfoy** [comment]
Okay, this is a bit more clear.

But, in 1), the message is true. It did not find any documentation, and it tells what what might help it find documentation. It tells you there are missing libraries. The message is readable for the user.

And, in 2), the message tells you to install HTTP::Tiny. It tells you there are missing libraries. However, the message looks different than 1).  The message is readable for the user. However, your patch does not make this message look like that in 1). It's still a different message. The patch does not improve the situation and brings up other problems.

**Comment by briandfoy** [comment]
After thinking about this over the weekend, I haven't changed my opinion. I might reverse that at some future time, but as it is now, supporting existing behavior is more important. These sorts of core modules can be very sensitive to the slightest changes, so the potential benefit needs to be quite large.

**Pull request closed without merging**
